# Generated by Django 2.0.5 on 2018-06-01 05:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30)),
                ('ano', models.PositiveIntegerField(help_text='Use o formato: AAAA', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)])),
                ('alugado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Cor',
                'verbose_name_plural': 'Cores',
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('aluguel_carro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rental.Carro')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(auto_now=True)),
                ('km_rodadps', models.PositiveIntegerField()),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario')),
            ],
            options={
                'verbose_name': 'Aluguel',
                'verbose_name_plural': 'Alugueis',
            },
        ),
        migrations.CreateModel(
            name='Informacao',
            fields=[
                ('info_carro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rental.Carro')),
                ('tempo_de_uso', models.PositiveIntegerField()),
                ('km_rodados', models.PositiveIntegerField()),
                ('descricao_carro', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Informação',
                'verbose_name_plural': 'Informações',
            },
        ),
        migrations.AddField(
            model_name='marca',
            name='marca_carro_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Carro'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='carro_imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Carro'),
        ),
        migrations.AddField(
            model_name='carro',
            name='cor_carro_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Cor'),
        ),
    ]
