# Generated by Django 2.0.5 on 2018-05-31 05:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ano', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)])),
                ('alugado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('carro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rental.Carro')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(auto_now=True)),
                ('km_rodadps', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Aluguel',
                'verbose_name_plural': 'Alugueis',
            },
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('carro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rental.Carro')),
                ('cor', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Cor',
                'verbose_name_plural': 'Cores',
            },
        ),
        migrations.CreateModel(
            name='Informacao',
            fields=[
                ('carro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rental.Carro')),
                ('tempo_de_uso', models.PositiveIntegerField()),
                ('km_rodados', models.PositiveIntegerField()),
                ('descricao_carro', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Informação',
                'verbose_name_plural': 'Informações',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('carro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rental.Carro')),
                ('marca', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
    ]
